CREATE TABLE COLOR (
  CODIGO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  DESCRIPCION VARCHAR(50) NOT NULL,
  RED INTEGER UNSIGNED NOT NULL,
  GREEN INTEGER UNSIGNED NOT NULL,
  BLUE INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(CODIGO)
);

CREATE TABLE INDICADOR (
  CODIGO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  DESCRIPCION VARCHAR(500) NULL,
  PADRE INTEGER UNSIGNED NULL,
  TIPO VARCHAR(20) NOT NULL DEFAULT 'folder',
  PRIMARY KEY(CODIGO),
  INDEX INDICADOR_PADRE_FK(PADRE),
  FOREIGN KEY(PADRE)
    REFERENCES INDICADOR(CODIGO)
      ON DELETE CASCADE
      ON UPDATE CASCADE
);

CREATE TABLE GRAFICO (
  CODIGO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  INDICADOR INTEGER UNSIGNED NOT NULL,
  TIPO VARCHAR(20) NOT NULL,
  PRIMARY KEY(CODIGO),
  INDEX GRAFICO_INDICADOR_FK(INDICADOR),
  FOREIGN KEY(INDICADOR)
    REFERENCES INDICADOR(CODIGO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE DETALLE_GRAFICO (
  CODIGO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  DESCRIPCION VARCHAR(500) NULL,
  GRAFICO INTEGER UNSIGNED NULL,
  PADRE INTEGER UNSIGNED NULL,
  VALOR DOUBLE NULL,
  PRIMARY KEY(CODIGO),
  INDEX DETALLE_GRAFICO_GRAFICO_FK(GRAFICO),
  INDEX DETALLE_GRAFICO_PADRE_FK(PADRE),
  FOREIGN KEY(GRAFICO)
    REFERENCES GRAFICO(CODIGO)
      ON DELETE CASCADE
      ON UPDATE CASCADE,
  FOREIGN KEY(PADRE)
    REFERENCES DETALLE_GRAFICO(CODIGO)
      ON DELETE CASCADE
      ON UPDATE CASCADE
);